# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leIrQD5uf_s27ATB9hUiAY9C7sMOGBmM
"""

import yfinance as yf
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

def load_data(ticker="AAPL", period="1y"):
    df = yf.download(ticker, period=period)
    data = df["Close"].values.reshape(-1, 1)
    scaler = MinMaxScaler()
    data_scaled = scaler.fit_transform(data)

    x, y = [], []
    for i in range(60, len(data_scaled)):
        x.append(data_scaled[i-60:i])
        y.append(data_scaled[i])

    return np.array(x), np.array(y), scaler